CREATE TABLE roles(

 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 name VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO roles (name) VALUES
    ('TENANT_ADMIN'),
    ('EMPLOYEE'),
    ('REQUESTER'),
    ('TECHNICIAN');